# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Diego Trazzi
email: diegotrazzi@gmail.com
description: Senior Engineer and Computer Graphics Expert with over 25 years of experience leading teams to deliver innovative, high-performance 3D and VR solutions. Skilled in managing cross-functional teams, developing proprietary frameworks, and mentoring engineers across disciplines. Proven success driving projects for Oscar-winning visual effects and advancing technology at top companies, including Apple, Unity, and Weta Digital. Proficient in C/Objective-C, Swift, Python, and real-time engines like Unity and Unreal, adept at solving complex technical challenges. Passionate about fostering collaborative environments, driving product excellence, and shaping the future of immersive AR/VR experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://diegotrazzi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: trazzidiego
github_username:  diegotrazzi
logo: https://avatars.githubusercontent.com/u/1245572?v=4
show_downloads: true

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Diego Trazzi
  email: diegotrazzi@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/trazzidiego # change to your Twitter homepage
    - https://github.com/diegotrazzi # change to your GitHub homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/diegotrazzi


# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
